from idlelib.replace import replace
#question 1
fruits=[]
a= input("enter fruit name 1:")
fruits.append(a)
b= input("enter fruit name 2:")
fruits.append(b)
c= input("enter fruit name 3:")
fruits.append(c)
d= input("enter fruit name 4:")
fruits.append(d)
e= input("enter fruit name 5:")
fruits.append(e)
f= input("enter fruit name 6:")
fruits.append(f)
g= input("enter fruit name 7:")
fruits.append(g)
h= input("enter fruit name 8:")
fruits.append(h)
print(fruits)
#question 2
marks=[]
v=int (input("enter marks of student 1:"))
marks.append(v)
u=int (input("enter marks of student 2:"))
marks.append(u)
y=int (input("enter marks of student 3:"))
marks.append(y)
x=int (input("enter marks of student 4:"))
marks.append(x)
w=int (input("enter marks of student 5:"))
marks.append(w)
z=int (input("enter marks of student 6:"))
marks.append(z)
print(marks)
marks.sort()
print(marks)
